{"uuid": "78c72cf6-350a-471d-a432-ac49ece1a5e1", "children": ["603bfa09-3119-4dbf-8304-dcdc4c6f208c", "94650e3e-db47-4e9e-b555-3c14ab5d0c7e"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\Sarang\\.wdm\\drivers\\chromedriver\\win32\\101.0.4951.41\\chromedriver.exe unexpectedly exited. Status code was: 3221225794\n\n", "trace": "  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Github repos\\python\\python-pytest\\conftest.py\", line 21, in test_setup\n    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 70, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 90, in __init__\n    self.service.start()\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 98, in start\n    self.assert_process_still_running()\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 110, in assert_process_still_running\n    raise WebDriverException(\n"}, "start": 1652511059722, "stop": 1652511062580}], "start": 1652511059722, "stop": 1652511062705}