{"uuid": "1e74ba65-5d9c-4661-98a3-670cce383f95", "children": ["11e11f52-aa49-4c0d-9629-3f5ab97f8802"], "befores": [{"name": "test_setup", "status": "passed", "start": 1652508322845, "stop": 1652508326884}], "afters": [{"name": "test_setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=101.0.4951.67)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0041B8F3+2406643]\n\tOrdinal0 [0x003AAF31+1945393]\n\tOrdinal0 [0x0029C610+837136]\n\tOrdinal0 [0x00290442+787522]\n\tOrdinal0 [0x00283F21+737057]\n\tOrdinal0 [0x002EA6F0+1156848]\n\tOrdinal0 [0x002E4243+1131075]\n\tOrdinal0 [0x002BE636+976438]\n\tOrdinal0 [0x002BF546+980294]\n\tGetHandleVerifier [0x00689612+2498066]\n\tGetHandleVerifier [0x0067C920+2445600]\n\tGetHandleVerifier [0x004B4F2A+579370]\n\tGetHandleVerifier [0x004B3D36+574774]\n\tOrdinal0 [0x003B1C0B+1973259]\n\tOrdinal0 [0x003B6688+1992328]\n\tOrdinal0 [0x003B6775+1992565]\n\tOrdinal0 [0x003BF8D1+2029777]\n\tBaseThreadInitThunk [0x7799FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77C27A7E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77C27A4E+238]\n\n", "trace": "  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\_pytest\\fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Github repos\\python\\python-pytest\\conftest.py\", line 26, in test_setup\n    driver.close()\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 938, in close\n    self.execute(Command.CLOSE)\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1652508330751, "stop": 1652508335475}], "start": 1652508322845, "stop": 1652508335475}