{"uuid": "55779c98-0291-4657-90c3-bbc533c17065", "children": ["ec2515f0-d849-4377-8fd4-bcd69b4fd90c", "efc5de8f-0760-44a0-9972-b853dadbadbb"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\Sarang\\.wdm\\drivers\\chromedriver\\win32\\101.0.4951.41\\chromedriver.exe unexpectedly exited. Status code was: 3221225794\n\n", "trace": "  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Github repos\\python\\python-pytest\\conftest.py\", line 21, in test_setup\n    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 70, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 90, in __init__\n    self.service.start()\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 98, in start\n    self.assert_process_still_running()\n  File \"D:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 110, in assert_process_still_running\n    raise WebDriverException(\n"}, "start": 1652510903398, "stop": 1652510906231}], "start": 1652510903398, "stop": 1652510906353}